// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waazgjvjnhtfufhxzegf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYXpnanZqbmh0ZnVmaHh6ZWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjEwMTUsImV4cCI6MjA3NDEzNzAxNX0.xkdSVs47ztdOodVSHs_iYdaOu4PVeui98yVYnaF0RUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});